//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class exam
    {
        public int exam_id { get; set; }
        public string name { get; set; }
        public System.DateTime create_time { get; set; }
        public int single_question_score { get; set; }
        public int quantity { get; set; }
        public int total_score { get; set; }
        public int duration { get; set; }
        public string description { get; set; }
        public int pass_score { get; set; }
    }
}
