//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public int id { get; set; }
        public string username { get; set; }
        public int exam_id { get; set; }
        public int grade { get; set; }
        public System.DateTime attend_time { get; set; }
        public System.DateTime end_time { get; set; }
        public int current_exampaper_question_id { get; set; }
        public bool is_finished { get; set; }
    }
}
