//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OESEntities : DbContext
    {
        public OESEntities()
            : base("name=OESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<exam> exam { get; set; }
        public DbSet<exampaper> exampaper { get; set; }
        public DbSet<question> question { get; set; }
        public DbSet<recordanswer> recordanswer { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<score> score { get; set; }
        public DbSet<user> user { get; set; }
    }
}
